From jupyter/datascience-notebook 
MAINTAINER Taku Yoshioka <contact@google.com>

USER root

RUN apt-get update && \
    apt-get install -y apt-utils && \
    apt-get install -y net-tools

RUN conda install -c conda-forge nbpresent
