FROM gcr.io/tensorflow/tensorflow:1.4.1
MAINTAINER Taku Yoshioka <taku.yoshioka.4096@gmail.com>

USER root

# Basic tools
RUN pip install opencv-python
RUN apt update
RUN apt install -y libsm6 libxext6 libxrender1
